import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { FsWorkspaceError } from './errors'

/** Phase-keyed workspace subdirs (mirrors PHASES-WORKFLOW.md). */
export const WORKSPACE_SUBDIRS = [
  '01-sales',
  '02-kickoff',
  '03-design',
  '04-architecture',
  '05-build',
  '06-qa-deploy',
  '07-handoff',
] as const

export function sanitizeCode(code: string): string {
  const clean = code.replace(/[^A-Za-z0-9_-]/g, '')
  if (!clean) {
    throw new FsWorkspaceError('invalid_path', `Invalid project code for workspace path: '${code}'`)
  }
  return clean
}

export function workspacePathFor(workspacesRoot: string, projectCode: string): string {
  return join(workspacesRoot, sanitizeCode(projectCode))
}

export function assertEmptyOrMissing(path: string): void {
  if (!existsSync(path)) return
  let entries: string[]
  try {
    entries = readdirSync(path)
  } catch (err) {
    throw new FsWorkspaceError(
      'invalid_path',
      `Cannot read workspace folder '${path}': ${(err as Error).message}`,
    )
  }
  const visible = entries.filter((name) => !name.startsWith('.'))
  if (visible.length > 0) {
    throw new FsWorkspaceError(
      'invalid_path',
      `Workspace folder '${path}' is not empty. Pick a fresh folder or move the contents elsewhere.`,
    )
  }
}

export function scaffoldWorkspace(root: string, projectCode: string): string {
  for (const sub of WORKSPACE_SUBDIRS) {
    mkdirSync(join(root, sub), { recursive: true })
  }
  const readmePath = join(root, 'README.md')
  if (!existsSync(readmePath)) {
    writeFileSync(readmePath, renderWorkspaceReadme(projectCode), 'utf-8')
  }
  return root
}

function renderWorkspaceReadme(projectCode: string): string {
  return [
    `# Workspace · ${projectCode}`,
    '',
    'Project root folder. One living document per phase. Updates rewrite the',
    'same file; history lives in git. No intermediate files.',
    '',
    '- `01-sales/quote.md` — F1 living document.',
    '- `02-kickoff/plan.md` (+ cronograma.md) — F2 living document.',
    '- `03-design/design-approval.md` — F3 living document.',
    '- `04-architecture/architecture.md` (+ diagrams/, scaffolds/) — F4 living document.',
    '- `05-build/<STORY_ID>/` — story brief + per-task dev-evidence.',
    '- `06-qa-deploy/<STORY_ID>/<TASK_ID>/` — qa-evidence + prod-evidence + deploy log.',
    '- `07-handoff/handoff.md` (+ client-acceptance.md) — F7 living document.',
    '',
    '_Generated by Tortuga OS when the project is instantiated._',
    '',
  ].join('\n')
}

export function agentCwdFor(workspacePath: string | null | undefined): string | null {
  if (!workspacePath) return null
  const scaffolds = join(workspacePath, '04-architecture', 'scaffolds')
  if (existsSync(scaffolds)) return scaffolds
  if (existsSync(workspacePath)) return workspacePath
  return null
}
